<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6pikosk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6pikosk/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6pikosk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6pikosk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6pikosk\appProdProjectContainer([
    'container.build_hash' => '6pikosk',
    'container.build_id' => '928001e2',
    'container.build_time' => 1629198391,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6pikosk');
